vim.keymap.set('n', '<leader>vG', '<cmd>lua require("config.vimspector").generate_debug_profile()<cr>')
vim.keymap.set('n', '<leader>vH', '<cmd>lua require("config.vimspector").toggle_human_mode()<cr>')
vim.keymap.set('n', '<leader>vI', '<cmd>VimspectorInstall<cr>')
vim.keymap.set('n', '<leader>vU', '<cmd>VimspectorUpdate<cr>')
vim.keymap.set('n', '<leader>vs', '<cmd>call vimspector#Launch()<cr>')
vim.keymap.set('n', '<leader>vS', '<cmd>call vimspector#Stop()<cr>')
vim.keymap.set('n', '<leader>vR', '<cmd>call vimspector#Resart()<cr>')
vim.keymap.set('n', '<leader>vx', '<cmd>call vimspector#Reset()<cr>')
vim.keymap.set('n', '<leader>vr', '<cmd>call vimspector#RunToCursor()<cr>')
vim.keymap.set('n', '<leader>vc', '<cmd>call vimspector#Continue()<cr>')
vim.keymap.set('n', '<leader>vi', '<cmd>call vimspector#StepInto()<cr>')
vim.keymap.set('n', '<leader>vo', '<cmd>call vimspector#StepOver()<cr>')
vim.keymap.set('n', '<leader>vu', '<cmd>call vimspector#StepOut()<cr>')
vim.keymap.set('n', '<leader>vb', '<cmd>call vimspector#ToggleBreakpoint()<cr>')

