vim.keymap.set('n', '<leader>dG', '<cmd>lua require("config.vimspector").generate_debug_profile()<cr>')
vim.keymap.set('n', '<leader>dH', '<cmd>lua require("config.vimspector").toggle_human_mode()<cr>')
vim.keymap.set('n', '<leader>dI', '<cmd>VimspectorInstall<cr>')
vim.keymap.set('n', '<leader>dU', '<cmd>VimspectorUpdate<cr>')
vim.keymap.set('n', '<leader>ds', '<cmd>call vimspector#Launch()<cr>')
vim.keymap.set('n', '<leader>dS', '<cmd>call vimspector#Stop()<cr>')
vim.keymap.set('n', '<leader>dR', '<cmd>call vimspector#Restart()<cr>')
vim.keymap.set('n', '<leader>dx', '<cmd>call vimspector#Reset()<cr>')
vim.keymap.set('n', '<leader>dr', '<cmd>call vimspector#RunToCursor()<cr>')
vim.keymap.set('n', '<leader>dc', '<cmd>call vimspector#Continue()<cr>')
vim.keymap.set('n', '<leader>di', '<cmd>call vimspector#StepInto()<cr>')
vim.keymap.set('n', '<leader>do', '<cmd>call vimspector#StepOver()<cr>')
vim.keymap.set('n', '<leader>du', '<cmd>call vimspector#StepOut()<cr>')
vim.keymap.set('n', '<leader>db', '<cmd>call vimspector#ToggleBreakpoint()<cr>')

